#! /bin/sh

# AutoStart
pgrep -x sxhkd >/dev/null || sxhkd &
# picom --experimental-backend &

# Bar
~/.config/polybar/launch.sh

# Monitor
bspc monitor -d I II III IV V VI VII VIII IX

# Configs
bspc config border_width 0
bspc config window_gap 8
bspc config split_ratio 0.50
bspc config top_padding 0
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0
bspc config border_width 1
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config pointer_follows_focus false
bspc config focus_follows_pointer true
bspc config normal_border_color "#FF0000"
bspc config focused_border_color "#00FF00"
bspc config urgent_border_color "#B58900"
bspc config presel_border_color "#26E2FF"
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

# Rules
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# dunst
killall dunst
../dunst/bspdunst.sh
